apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <EksClusterName>
  region: sa-east-1

managedNodeGroups:
  - name: <NodegroupName>
    desiredCapacity: 1
# Using spot instances and selecting ec2 instance types
    spot: true
    instanceTypes: 
    - t3.small
#    - t2.small
#    - t3.medium
#    - t2.medium
    maxPodsPerNode: 110
    ssh:
      enableSsm: true
    privateNetworking: true # This must be set to 'true' when only 'Private' subnets has been configured on the EKS Cluster config file